name: .NET Build

on:
  push:
    branches: ['*']
    tags-ignore: ['*']
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.201

      - name: Restore dependencies
        run: dotnet restore

      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData/XIVLauncher/addon/Hooks/dev/"

      - name: Edit package manifest
        run: |
          $ver = (Invoke-Expression 'git describe --tags')
          $path = './src/Microdancer.json'
          $content = Get-Content -path $path
          $content = $content -replace '1.0.0.0',$ver
          Set-Content -Path $path -Value $content

      - name: Build
        run: |
          $ver = (Invoke-Expression 'git describe --tags')
          Invoke-Expression 'dotnet build --no-restore --configuration Release --nologo -p:Version=$ver -p:FileVersion=$ver'

      - name: Create repo manifest
        run: |
          $ver = (Invoke-Expression 'git describe --tags')
          $path = './base_repo.json'
          $new_path = './bin/Release/Microdancer/Microdancer.json'
          $content = Get-Content -path $path
          $content = $content -replace '1.0.0.0',$ver
          Set-Content -Path $new_path -Value $content

      - name: Upload to S3
        uses: reggionick/s3-deploy@v3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          folder: bin/Release/Microdancer
          bucket: ${{ secrets.AWS_S3_BUCKET }}
          bucket-region: us-east-1
          no-cache: true

