name: Microdancer

on:
  push:
    branches: ['*']
    tags-ignore: ['*']

jobs:

  build-and-deploy:
    env:
      ProgressPreference: "SilentlyContinue"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.201

      - name: Restore dependencies
        env:
          HUSKY: 0
        run: |
          $PSStyle.OutputRendering = [System.Management.Automation.OutputRendering]::PlainText;
          dotnet restore
        shell: pwsh

      - name: Download Dalamud
        run: |
          $PSStyle.OutputRendering = [System.Management.Automation.OutputRendering]::PlainText;
          Invoke-WebRequest https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
          Expand-Archive -Path latest.zip -DestinationPath dalamud-distrib
        shell: pwsh

      - name: Edit package manifest
        run: |
          $PSStyle.OutputRendering = [System.Management.Automation.OutputRendering]::PlainText;
          $ver = (./scripts/get-version.ps1).Version
          $path = './src/Microdancer.json'
          $content = Get-Content -path $path
          $content = $content -replace '1.0.0.0',$ver
          Set-Content -Path $path -Value $content
        shell: pwsh

      - name: Build
        run: |
          $PSStyle.OutputRendering = [System.Management.Automation.OutputRendering]::PlainText;
          $ver = (./scripts/get-version.ps1).Version
          Invoke-Expression 'dotnet build --no-restore --configuration Release --nologo -p:Version=$ver -p:AssemblyVersion=$ver -p:FileVersion=$ver'
        shell: pwsh

      - name: Create icon
        run: |
          Copy-Item 'images/icon.png' 'bin/Release/Microdancer/icon.png'
        shell: pwsh

      - name: Create repo manifest
        run: |
          $PSStyle.OutputRendering = [System.Management.Automation.OutputRendering]::PlainText;
          $ver = (./scripts/get-version.ps1).Version
          $path = './base_repo.json'
          $new_path = './bin/Release/Microdancer/Microdancer.json'
          $content = Get-Content -path $path
          $content = $content -replace '1.0.0.0',$ver
          Set-Content -Path $new_path -Value $content
        shell: pwsh

      - name: Upload to S3
        uses: reggionick/s3-deploy@v3
        if: ${{ !env.ACT }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          folder: bin/Release/Microdancer
          bucket: ${{ secrets.AWS_S3_BUCKET }}
          bucket-region: us-east-1
          no-cache: true

